apiVersion: v1
kind: PersistentVolume
metadata:
  name: database
  labels:
    volume: my-volume
spec:
  capacity:
    storage: 1Gi
  nfs:
    server: 192.168.1.8
    path: "/d/Shared"
  accessModes:
    - ReadWriteMany
